
# Applied Review — Data Inspection, Cleaning, and Aggregation

This notebook applies the Pandas skills learned in Days 3–5 to a larger synthetic XR moral decision-making dataset.

Rather than practicing isolated commands, the goal is to reproduce a basic research-data workflow: inspect the raw data, identify data-quality problems, clean the dataset while documenting decisions, and generate condition-level behavioral summaries.

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("/content/vr_moral_dilemma_large_dirty.csv")

The dataset has total 12 variables. "participant_id", "embodiment_score", "presence_score", "agency_score", conflict_score", "gaze_switches", "gaze_time_sheep", and "gaze_time_farmer" variables are numeric. On the other hand, "condition", "choice", "decision_time", and "first_fixation" variables are categorical. But,"decision_time" should be numerical data.

In [6]:
df.head()
df.shape
df.info()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   participant_id    163 non-null    int64
 1   condition         163 non-null    object
 2   choice            163 non-null    object
 3   decision_time     162 non-null    object
 4   embodiment_score  162 non-null    float64
 5   presence_score    162 non-null    float64
 6   agency_score      163 non-null    float64
 7   conflict_score    163 non-null    float64
 8   gaze_switches     163 non-null    int64
 9   gaze_time_sheep   162 non-null    float64
 10  gaze_time_farmer  163 non-null    float64
 11  first_fixation    163 non-null    object
dtypes: float64(6), int64(2), object(4)
memory usage: 15.4+ KB

Index(['participant_id', 'condition', 'choice', 'decision_time',
       'embodiment_score', 'presence_score', 'agency_score', 'conflict_score',
       'gaze_switches', 'gaze_time_sheep', 'gaze_time_farmer',
       'first_fixation'],
      dtype='object')

There are inconsistant labels in the condition variable.

```
# Bu, kod olarak biçimlendirilmiştir
```

In [7]:
df["condition"].unique()

array(['sheep', 'farmer', 'Sheep', 'farmr'], dtype=object)

In [8]:

df["condition"].value_counts()

condition
sheep     81
farmer    80
Sheep      1
farmr      1
Name: count, dtype: int64

Only one different label exists in choice variable, should be corrected

In [9]:
df["choice"].unique()

array(['save_sheep', 'save_farmer', 'Save_Sheep'], dtype=object)

In [10]:

df["choice"].value_counts()

choice
save_sheep     91
save_farmer    71
Save_Sheep      1
Name: count, dtype: int64

In [11]:


df["first_fixation"].value_counts()

first_fixation
sheep     84
farmer    79
Name: count, dtype: int64

No inconsistent labels.

In [12]:
df["first_fixation"].unique()

array(['sheep', 'farmer'], dtype=object)

Missing values in each affected column are approximately equal to %0.6 percentage.

In [13]:
df.isna().sum()  / len(df) * 100

participant_id      0.000000
condition           0.000000
choice              0.000000
decision_time       0.613497
embodiment_score    0.613497
presence_score      0.613497
agency_score        0.000000
conflict_score      0.000000
gaze_switches       0.000000
gaze_time_sheep     0.613497
gaze_time_farmer    0.000000
first_fixation      0.000000
dtype: float64

In [14]:
df.duplicated().sum()

np.int64(3)

In [15]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
158    False
159    False
160     True
161     True
162     True
Length: 163, dtype: bool

"decision_time" is a numerical data. Here, there is a datatype problem which needed to be converted

In [16]:
df.dtypes

participant_id        int64
condition            object
choice               object
decision_time        object
embodiment_score    float64
presence_score      float64
agency_score        float64
conflict_score      float64
gaze_switches         int64
gaze_time_sheep     float64
gaze_time_farmer    float64
first_fixation       object
dtype: object

In the "decision_time" we can see other than numerical data, one value in Nan and we have another "missing" value.

In [17]:
df["decision_time"].unique()

array(['3.77', '2.44', '4.55', '4.9', '4.69', '5.07', '5.45', nan, '4.1',
       '2.24', '3.59', '4.13', '4.05', '4.01', '5.21', '5.46', '3.7',
       '3.21', '3.73', '19.6', '3.62', '1.2', '1.93', '3.39', '4.34',
       '2.75', '2.15', '5.11', '3.66', '6.51', '4.45', '3.71', '4.63',
       '3.24', '2.92', '3.93', '4.39', '3.31', '3.65', '2.5', '4.44',
       '3.57', '3.23', '3.07', '4.17', '3.97', '2.22', '2.65', '4.7',
       '3.28', '2.53', '3.56', '4.08', '2.94', '2.81', '2.77', '3.82',
       '2.71', '3.72', '3.8', '1.95', '4.47', '6.07', '4.23', '4.88',
       'missing', '3.22', '4.46', '4.62', '5.02', '2.89', '4.6', '3.84',
       '4.11', '6.32', '3.58', '3.99', '2.67', '4.67', '3.67', '2.79',
       '3.3', '2.12', '4.35', '3.53', '3.27', '1.65', '1.4', '3.43',
       '27.4', '3.01', '3.92', '4.42', '1.9', '2.6', '4.36', '2.86',
       '3.95', '3.12', '3.44', '2.78', '2.73', '3.2', '3.75', '3.08',
       '1.74', '3.38', '3.86', '5.88', '2.06', '5.83', '4.25', '3.96',
       '5.14', '3.41', '5.26', '2.98', '5.18', '2.83', '3.49', '3.14',
       '3.17', '2.8', '1.54', '4.3', '5.81', '6.48', '4.31', '3.45',
       '2.82', '3.76', '2.26'], dtype=object)

In [18]:
df["decision_time"] = pd.to_numeric(df["decision_time"], errors = "coerce")

After the conversion, we see only one nan because all the non-numeric values converted into one nan. But, when check the missing values, it counts each missing value still since we did not converted into a non-nan value.

In [19]:
df["decision_time"].unique()

array([ 3.77,  2.44,  4.55,  4.9 ,  4.69,  5.07,  5.45,   nan,  4.1 ,
        2.24,  3.59,  4.13,  4.05,  4.01,  5.21,  5.46,  3.7 ,  3.21,
        3.73, 19.6 ,  3.62,  1.2 ,  1.93,  3.39,  4.34,  2.75,  2.15,
        5.11,  3.66,  6.51,  4.45,  3.71,  4.63,  3.24,  2.92,  3.93,
        4.39,  3.31,  3.65,  2.5 ,  4.44,  3.57,  3.23,  3.07,  4.17,
        3.97,  2.22,  2.65,  4.7 ,  3.28,  2.53,  3.56,  4.08,  2.94,
        2.81,  2.77,  3.82,  2.71,  3.72,  3.8 ,  1.95,  4.47,  6.07,
        4.23,  4.88,  3.22,  4.46,  4.62,  5.02,  2.89,  4.6 ,  3.84,
        4.11,  6.32,  3.58,  3.99,  2.67,  4.67,  3.67,  2.79,  3.3 ,
        2.12,  4.35,  3.53,  3.27,  1.65,  1.4 ,  3.43, 27.4 ,  3.01,
        3.92,  4.42,  1.9 ,  2.6 ,  4.36,  2.86,  3.95,  3.12,  3.44,
        2.78,  2.73,  3.2 ,  3.75,  3.08,  1.74,  3.38,  3.86,  5.88,
        2.06,  5.83,  4.25,  3.96,  5.14,  3.41,  5.26,  2.98,  5.18,
        2.83,  3.49,  3.14,  3.17,  2.8 ,  1.54,  4.3 ,  5.81,  6.48,
        4.31,  3.45,  2.82,  3.76,  2.26])

In [20]:
df.isna().sum()

participant_id      0
condition           0
choice              0
decision_time       2
embodiment_score    1
presence_score      1
agency_score        0
conflict_score      0
gaze_switches       0
gaze_time_sheep     1
gaze_time_farmer    0
first_fixation      0
dtype: int64

It requires us to change the typo and the. capital letters.

In [21]:
df["condition"].unique()

array(['sheep', 'farmer', 'Sheep', 'farmr'], dtype=object)

This one requires us to change the capital letter.

In [22]:
df["choice"].unique()

array(['save_sheep', 'save_farmer', 'Save_Sheep'], dtype=object)

In [23]:
df["condition"] = df["condition"].str.lower()

In [24]:
df["choice"] = df["choice"].str.lower()

In [25]:
df["condition"] = df["condition"].replace({ "farmr" : "farmer"})

In [26]:
df["condition"].unique()

array(['sheep', 'farmer'], dtype=object)

In [27]:
df["choice"].unique()

array(['save_sheep', 'save_farmer'], dtype=object)

The inconsisted labels are corrected.

In [28]:
df[
    (df["embodiment_score"] < 1) |
    (df["embodiment_score"] > 7)
]

,participant_id,condition,choice,decision_time,embodiment_score,presence_score,agency_score,conflict_score,gaze_switches,gaze_time_sheep,gaze_time_farmer,first_fixation
76,1077,farmer,save_farmer,3.84,8.2,5.36,4.86,4.34,12,4.49,4.38,sheep

In [29]:
df[
    (df["agency_score"] < 1) |
    (df["agency_score"] > 7)
]

,participant_id,condition,choice,decision_time,embodiment_score,presence_score,agency_score,conflict_score,gaze_switches,gaze_time_sheep,gaze_time_farmer,first_fixation
133,1134,sheep,save_sheep,3.96,5.52,3.69,0.4,5.32,20,7.94,6.52,sheep

In [30]:
df[
    (df["conflict_score"] < 1) |
    (df["conflict_score"] > 7)
]

,participant_id,condition,choice,decision_time,embodiment_score,presence_score,agency_score,conflict_score,gaze_switches,gaze_time_sheep,gaze_time_farmer,first_fixation
31,1032,sheep,save_farmer,4.45,5.33,5.5,5.79,7.8,22,5.98,6.74,sheep

In [31]:
df["decision_time"].describe()

count    161.000000
mean       3.933727
std        2.470709
min        1.200000
25%        3.010000
50%        3.710000
75%        4.360000
max       27.400000
Name: decision_time, dtype: float64

participant 1021 and 1104 has high scores.

In [32]:
df.sort_values("decision_time")

,participant_id,condition,choice,decision_time,embodiment_score,presence_score,agency_score,conflict_score,gaze_switches,gaze_time_sheep,gaze_time_farmer,first_fixation
22,1023,sheep,save_sheep,1.20,5.82,4.78,3.25,4.86,21,8.30,4.88,sheep
121,1122,farmer,save_farmer,1.20,3.81,5.91,4.33,1.92,19,4.48,10.01,sheep
99,1100,sheep,save_farmer,1.40,7.00,5.65,4.53,4.05,16,5.08,7.57,sheep
146,1147,farmer,save_farmer,1.54,3.94,4.26,7.00,3.73,16,5.83,7.10,farmer
97,1098,sheep,save_sheep,1.65,5.77,5.31,6.19,4.34,18,5.49,4.44,sheep
...,...,...,...,...,...,...,...,...,...,...,...,...
30,1031,sheep,save_sheep,6.51,6.44,4.64,4.35,6.12,20,5.08,10.16,farmer
20,1021,farmer,save_farmer,19.60,6.44,6.95,6.46,4.58,15,7.38,5.95,sheep
103,1104,sheep,save_sheep,27.40,4.60,5.79,5.29,5.05,24,6.61,4.88,farmer
7,1008,farmer,save_farmer,NaN,5.21,5.55,4.61,4.56,15,6.22,4.33,farmer
67,1068,farmer,save_sheep,NaN,6.25,6.09,6.01,4.02,18,6.10,7.03,farmer

In [33]:
df["gaze_switches"].describe()

count    163.000000
mean      18.220859
std        4.749301
min        9.000000
25%       16.000000
50%       18.000000
75%       20.500000
max       58.000000
Name: gaze_switches, dtype: float64

Participant 1146 showed an unusually high number of gaze switches compared with the rest of the sample.

In [34]:
df.sort_values("gaze_switches")

,participant_id,condition,choice,decision_time,embodiment_score,presence_score,agency_score,conflict_score,gaze_switches,gaze_time_sheep,gaze_time_farmer,first_fixation
55,1056,farmer,save_farmer,2.94,5.46,4.96,4.53,3.49,9,5.45,7.78,farmer
127,1128,farmer,save_sheep,2.06,5.17,5.64,5.54,4.24,9,7.66,4.29,farmer
130,1131,sheep,save_sheep,3.65,5.42,6.44,5.99,4.12,10,5.37,6.98,sheep
42,1043,farmer,save_sheep,3.57,4.99,6.00,4.97,4.71,11,5.90,7.74,farmer
129,1130,farmer,save_farmer,3.27,6.27,6.50,5.96,4.10,11,7.08,6.03,farmer
...,...,...,...,...,...,...,...,...,...,...,...,...
39,1040,sheep,save_sheep,3.65,6.40,4.92,5.82,4.99,24,7.07,2.28,sheep
64,1065,sheep,save_farmer,6.07,5.57,5.28,5.53,6.45,25,8.98,4.63,farmer
138,1139,sheep,save_sheep,5.18,6.46,7.00,6.09,7.00,25,6.72,5.47,farmer
79,1080,sheep,save_sheep,6.32,5.07,6.59,5.97,7.00,32,8.06,4.53,sheep
145,1146,farmer,save_farmer,3.59,5.30,6.87,4.44,5.09,58,4.73,6.18,farmer

In [35]:
clean_df = df.copy()

In [36]:
clean_df = clean_df.drop_duplicates()

In [37]:
clean_df.duplicated().sum()

np.int64(0)

In [38]:
clean_df.isna().sum()

participant_id      0
condition           0
choice              0
decision_time       2
embodiment_score    1
presence_score      1
agency_score        0
conflict_score      0
gaze_switches       0
gaze_time_sheep     1
gaze_time_farmer    0
first_fixation      0
dtype: int64

In [39]:
clean_df = clean_df.dropna()

In [40]:
clean_df.isna().sum()

participant_id      0
condition           0
choice              0
decision_time       0
embodiment_score    0
presence_score      0
agency_score        0
conflict_score      0
gaze_switches       0
gaze_time_sheep     0
gaze_time_farmer    0
first_fixation      0
dtype: int64

In [41]:
clean_df = clean_df[
    clean_df["embodiment_score"].between(1, 7)
    & clean_df["presence_score"].between(1, 7)
    & clean_df["agency_score"].between(1, 7)
    & clean_df["conflict_score"].between(1, 7)
]

In [42]:
clean_df[["embodiment_score", "presence_score", "agency_score", "conflict_score"]].describe()

       embodiment_score  presence_score  agency_score  conflict_score
count         152.00000      152.000000    152.000000      152.000000
mean            5.57375        5.490066      5.216184        4.738487
std             0.79013        0.753394      0.868252        0.935134
min             3.35000        3.280000      3.120000        1.920000
25%             5.05500        4.930000      4.530000        4.192500
50%             5.59500        5.510000      5.270000        4.740000
75%             6.06000        5.965000      5.832500        5.245000
max             7.00000        7.000000      7.000000        7.000000

In [43]:
print("Raw dataset:", df.shape)
print("Clean dataset:", clean_df.shape)

Raw dataset: (163, 12)
Clean dataset: (152, 12)

In [44]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 152 entries, 0 to 159
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   participant_id    152 non-null    int64
 1   condition         152 non-null    object
 2   choice            152 non-null    object
 3   decision_time     152 non-null    float64
 4   embodiment_score  152 non-null    float64
 5   presence_score    152 non-null    float64
 6   agency_score      152 non-null    float64
 7   conflict_score    152 non-null    float64
 8   gaze_switches     152 non-null    int64
 9   gaze_time_sheep   152 non-null    float64
 10  gaze_time_farmer  152 non-null    float64
 11  first_fixation    152 non-null    object
dtypes: float64(7), int64(2), object(3)
memory usage: 15.4+ KB

In [45]:
clean_df.head()

,participant_id,condition,choice,decision_time,embodiment_score,presence_score,agency_score,conflict_score,gaze_switches,gaze_time_sheep,gaze_time_farmer,first_fixation
0,1001,sheep,save_sheep,3.77,4.81,5.25,5.68,4.30,13,5.22,3.17,sheep
1,1002,farmer,save_sheep,2.44,5.17,6.34,3.87,3.32,17,5.59,6.07,sheep
2,1003,farmer,save_farmer,4.55,5.32,5.79,5.76,6.16,19,4.63,4.25,sheep
3,1004,sheep,save_sheep,4.90,5.41,5.40,4.42,6.58,20,7.48,6.46,sheep
4,1005,farmer,save_farmer,4.69,5.52,5.76,5.50,5.90,20,9.90,5.14,farmer

In [46]:
condition_grp = df.groupby(["condition"])

In [47]:
condition_grp.get_group("sheep")

/tmp/ipykernel_501/967303938.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  condition_grp.get_group("sheep")

,participant_id,condition,choice,decision_time,embodiment_score,presence_score,agency_score,conflict_score,gaze_switches,gaze_time_sheep,gaze_time_farmer,first_fixation
0,1001,sheep,save_sheep,3.77,4.81,5.25,5.68,4.30,13,5.22,3.17,sheep
3,1004,sheep,save_sheep,4.90,5.41,5.40,4.42,6.58,20,7.48,6.46,sheep
5,1006,sheep,save_farmer,5.07,6.18,6.96,4.09,5.31,22,4.63,5.78,farmer
9,1010,sheep,save_sheep,2.24,5.94,6.31,5.91,3.99,22,10.14,3.41,sheep
12,1013,sheep,save_sheep,4.05,7.00,5.48,6.53,4.14,21,6.31,4.72,sheep
...,...,...,...,...,...,...,...,...,...,...,...,...
152,1153,sheep,save_farmer,3.95,5.90,4.17,5.68,3.23,20,5.13,4.05,farmer
155,1156,sheep,save_sheep,4.39,6.40,6.46,5.93,5.22,24,5.85,5.74,sheep
157,1158,sheep,save_sheep,3.76,4.87,5.02,5.59,4.68,21,5.36,5.48,sheep
160,1010,sheep,save_sheep,2.24,5.94,6.31,5.91,3.99,22,10.14,3.41,sheep
161,1050,sheep,save_sheep,4.70,6.88,4.13,4.56,4.82,19,6.67,2.18,sheep

In [48]:
condition_grp[["decision_time","presence_score","conflict_score","embodiment_score","agency_score"]].agg(["mean","median","std"])

          decision_time                  presence_score                   \
                   mean median       std           mean median       std
condition
farmer         3.655949   3.58  1.998109       5.469875  5.545  0.743312
sheep          4.201341   3.94  2.840026       5.471585  5.450  0.778494

          conflict_score                  embodiment_score                   \
                    mean median       std             mean median       std
condition
farmer          4.608025   4.58  0.888238         5.437160   5.52  0.885014
sheep           4.881829   4.83  0.988949         5.729506   5.77  0.719140

          agency_score
                  mean median       std
condition
farmer        5.244815  5.290  0.845571
sheep         5.140976  5.235  1.035572

In [49]:
summary_table = condition_grp.agg(
    n=('participant_id', 'count'),
    decision_time_mean=('decision_time', 'mean'),
    decision_time_std=('decision_time', 'std'),
    conflict_mean=('conflict_score', 'mean'),
    embodiment_mean=('embodiment_score', 'mean'),
    gaze_switches_mean=('gaze_switches', 'mean')
)
display(summary_table)

,n,decision_time_mean,decision_time_std,conflict_mean,embodiment_mean,gaze_switches_mean
condition,,,,,,
farmer,81,3.655949,1.998109,4.608025,5.437160,17.148148
sheep,82,4.201341,2.840026,4.881829,5.729506,19.280488

In [50]:
choice_behavior = condition_grp["choice"].value_counts(normalize=True)
print(choice_behavior)

condition  choice
farmer     save_farmer    0.567901
           save_sheep     0.432099
sheep      save_sheep     0.695122
           save_farmer    0.304878
Name: proportion, dtype: float64

the first fixation behavior looks descrpitively relavent between the condition and the first fixation in terms of embodiment manipulation

In [51]:
first_fixation_beh = condition_grp["first_fixation"].value_counts(normalize = True)
print(first_fixation_beh)

condition  first_fixation
farmer     farmer            0.543210
           sheep             0.456790
sheep      sheep             0.573171
           farmer            0.426829
Name: proportion, dtype: float64

In [60]:
filtered_df = clean_df[clean_df['choice'] == 'save_sheep']

# Group by 'condition' and calculate the mean of the specified columns
comparison_results = filtered_df.groupby('condition')[['decision_time', 'conflict_score', 'gaze_time_sheep']].mean()

display(comparison_results)

           decision_time  conflict_score  gaze_time_sheep
condition
farmer          3.342500        4.497187         5.993437
sheep           4.377308        4.955192         6.518654

In [61]:
double_grp = clean_df.groupby(["condition", "choice"])

In [62]:
double_grp[["decision_time", "conflict_score"]].mean()

                       decision_time  conflict_score
condition choice
farmer    save_farmer       3.873864        4.690000
          save_sheep        3.342500        4.497187
sheep     save_farmer       3.906667        4.679583
          save_sheep        4.377308        4.955192

In [63]:
clean_df.to_csv("vr_moral_dilemma_clean.csv", index = False)